services:
  db:
    container_name: esg-container
    image: "esg:spring-docker"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PROFILE=dev
      - DATABASE_URL=jdbc:mysql://fiap-api-hml.mysql.database.azure.com:3306/api?createDatabaseIfNotExist=true
      - DATABASE_USER=root
      - DATABASE_PWD=root_pass

