CREATE SEQUENCE DISPOSITIVO_IOT_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_DISPOSITIVO_IOT(
    ID INTEGER DEFAULT DISPOSITIVO_IOT_SEQ.NEXTVAL NOT NULL,
    NOME VARCHAR2(100) NOT NULL,
    MODELO VARCHAR(100) NOT NULL,
    FABRICANTE VARCHAR(100) NOT NULL
)